# name: Release

# on:
#   push:
#     branches:
#       - main

# jobs:
#   release:
#     name: "Create Releases"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Release Script
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           ./.github/workflows/scripts/release.sh
